# Generated by Django 5.1.4 on 2024-12-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('villa', 'Villa'), ('studio', 'Studio'), ('duplex', 'Duplex'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=50)),
                ('num_bedrooms', models.IntegerField(default=1)),
                ('num_bathrooms', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='realestate_images/')),
                ('status', models.CharField(default='Available', max_length=20)),
                ('sale_status', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10)),
            ],
        ),
    ]
